# Generated by Django 3.0.3 on 2020-03-18 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=6)),
                ('course_description', models.CharField(max_length=200)),
                ('course_department', models.CharField(max_length=50)),
                ('course_difficulty', models.IntegerField()),
                ('course_workload', models.IntegerField()),
                ('course_content_rating', models.IntegerField()),
                ('course_review', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_name', models.CharField(max_length=50)),
                ('prof_deparment', models.CharField(max_length=50)),
                ('prof_research_interest', models.CharField(max_length=50)),
                ('img_src', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaughtBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=200)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='rate.Courses')),
                ('prof_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof', to='rate.Professors')),
            ],
        ),
        migrations.CreateModel(
            name='ProfRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punctuality', models.IntegerField()),
                ('grading', models.IntegerField()),
                ('strictness', models.IntegerField()),
                ('teaching_skill', models.IntegerField()),
                ('enthusiasmInTeaching', models.IntegerField()),
                ('overall', models.IntegerField()),
                ('review', models.CharField(max_length=200)),
                ('prof_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.Professors')),
            ],
        ),
    ]
