# Generated by Django 3.0.3 on 2020-03-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professors',
            name='img_src',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professors',
            name='prof_research_interest',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='professors',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profrating',
            name='review',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='taughtby',
            name='review',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
