# Generated by Django 3.0.3 on 2020-03-20 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof_to_subj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_of_subj', models.IntegerField(blank=True, null=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.Professors')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.Courses')),
            ],
        ),
    ]
