# Generated by Django 3.0.3 on 2020-03-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20200318_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professors',
            name='img_src',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='professors',
            name='prof_research_interest',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professors',
            name='website',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profrating',
            name='review',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='taughtby',
            name='review',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
